# Camera Configuration
camera:
  resolution:
    width: 1640
    height: 1232
  framerate: 30
  format: "RGB888"
  
  # Single or dual camera mode
  dual_mode: true
  cameras: [0, 1]
  
  # Camera controls
  auto_exposure: true
  auto_white_balance: true
  
  # Face detection settings
  detection:
    confidence_threshold: 0.5
    nms_threshold: 0.4
    min_face_size: 40
