# Default Configuration
app:
  name: "Skipper Face Tracker"
  version: "2.0.0"
  
  # Logging
  log:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    file: "data/logs/skipper.log"
    max_bytes: 10485760  # 10MB
    backup_count: 5
    
  # Data directories
  paths:
    data: "data"
    logs: "data/logs"
    enrollment: "data/enrollment"
    cache: "data/cache"
    models: "models"
    face_db: "models/face_db/faces_db.pkl"
    
# Face Recognition
face_recognition:
  enabled: true
  database: "models/face_db/faces_db.pkl"
  threshold: 0.6  # similarity threshold
  update_interval: 5  # frames between recognition attempts
  
# Web Interface
web:
  enabled: true
  host: "0.0.0.0"
  port: 5000
  debug: false
  
# Performance
performance:
  # Threading
  use_threading: true
  max_workers: 4
  
  # Hailo optimization
  hailo:
    batch_size: 1
    async_mode: false
